backend:
  name: git-gateway
  branch: main
  publish_mode: simple
display_url: https://your-site-name.netlify.app

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Articles"
    folder: "_posts"
    create: true
    # This is the "secret sauce" that connects to your homepage
    tag: "blog" 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
     - {label: "Tags", name: "tags", widget: "hidden", default: ["blog"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "Admin"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
